### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by leandrowilliam** [tienne/webpack-hook-plugin#1]
I'm getting error using this way:
`import WebpackHookPlugin from 'webpack-hook-plugin';`

Error:
```
> app@0.0.1 build /mnt/c/Users/kript/projects/app
> webpack

/mnt/c/Users/kript/projects/app/webpack.config.js:11
import WebpackHookPlugin from "webpack-hook-plugin"
       ^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
```

Env

- OS: Ubuntu for WSL (Windos Subsytem for Linux) 18.04
- Node: v10.15.3
- Webpack: 4.32.0
- webpack-hook-plugin: 1.0.2

**Comment by leandrowilliam** [comment]
I try import as this way 👇 and work for me!

`const WebpackHookPlugin = require("webpack-hook-plugin").WebpackHookPlugin`

**Comment by tienne** [comment]
@leandrowilliam can you try with 1.0.6 version

**Comment by leandrowilliam** [comment]
I can use i as `const WebpackHookPlugin = require("webpack-hook-plugin")`
It's fixed! thanks
