### ISSUE TITLE
How does this compare to webpack-shell-plugin?

### ISSUE THREAD

**Issue by natterstefan** [tienne/webpack-hook-plugin#10]
Hi @tienne,

thanks for your solution. How does it compare with https://www.npmjs.com/package/webpack-shell-plugin? Does your solution solve some of the mentioned issues in their repo?

Thanks for your help.

**Comment by tienne** [comment]
@natterstefan 
no functional difference. However, `webpack-shell-plugin` is no longer being maintained.
Also, typescript is not supported, so created this plugin

**Comment by natterstefan** [comment]
Thanks for the feedback @tienne.
